name: Android Auditd CI

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: '选择构建类型'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release
      target_abi:
        description: '目标设备架构'
        required: true
        default: 'arm64-v8a'
        type: choice
        options:
          - armeabi-v7a
          - arm64-v8a
          - x86
          - x86_64
          
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      TARGET_ABI: ${{ github.event.inputs.target_abi || 'arm64-v8a' }}
      BUILD_TYPE: ${{ github.event.inputs.build_type || 'debug' }}

    steps:
    # 1. 检出代码
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. 设置 JDK 17 (修复：从11升级到17)
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 3. 安装 Android SDK 和 NDK (修复：使用替代方案)
    - name: Setup Android SDK and NDK
      run: |
        # 安装命令行工具
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-*.zip -d cmdline-tools
        mkdir -p android-sdk
        mv cmdline-tools android-sdk/cmdline-tools
        
        # 设置环境变量
        echo "ANDROID_HOME=$PWD/android-sdk" >> $GITHUB_ENV
        echo "PATH=$PWD/android-sdk/cmdline-tools/bin:$PATH" >> $GITHUB_ENV
        
        # 接受许可
        yes | sdkmanager --licenses
        
        # 安装指定版本的 NDK
        sdkmanager "ndk;25.1.8937393" --channel=0
        
        # 设置 NDK 路径
        echo "NDK_HOME=$PWD/android-sdk/ndk/25.1.8937393" >> $GITHUB_ENV
        echo "PATH=$PWD/android-sdk/ndk/25.1.8937393:$PATH" >> $GITHUB_ENV

    # 4. 设置构建类型变量
    - name: Set Gradle build type
      run: |
        if [ "$BUILD_TYPE" = "release" ]; then
          echo "GRADLE_BUILD_TYPE=Release" >> $GITHUB_ENV
        else
          echo "GRADLE_BUILD_TYPE=Debug" >> $GITHUB_ENV
        fi

    # 5. 编译原生组件
    - name: Build native binaries
      run: |
        echo "Building for $TARGET_ABI ($BUILD_TYPE)"
        export APP_ABI=$TARGET_ABI
        
        cd auditd && ./build.sh
        cd ../forensikmediator && ./build.sh
        cd ../audit-dispatch && ./build.sh
        
        find . -name "*.so" -o -name "auditd" -o -name "forensikmediator" -o -name "audit-dispatch"

    # 6. 编译 Android 应用
    - name: Build Android APK
      run: |
        cd AndroidForensik
        ./gradlew assemble$GRADLE_BUILD_TYPE
        ls -l app/build/outputs/apk/$GRADLE_BUILD_TYPE/

    # 7. 上传构建产物
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: auditd_binaries_${{ env.TARGET_ABI }}_${{ env.BUILD_TYPE }}
        path: |
          auditd/libs/
          forensikmediator/libs/
          audit-dispatch/libs/
          AndroidForensik/app/build/outputs/apk/$GRADLE_BUILD_TYPE/
