name: Android Auditd CI

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: '选择构建类型'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release
      target_abi:
        description: '目标设备架构'
        required: true
        default: 'arm64-v8a'
        type: choice
        options:
          - armeabi-v7a
          - arm64-v8a
          - x86
          - x86_64
          
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      TARGET_ABI: ${{ github.event.inputs.target_abi || 'arm64-v8a' }}
      BUILD_TYPE: ${{ github.event.inputs.build_type || 'debug' }}

    steps:
    # 1. 检出代码
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. 设置 Java 11 用于 Android SDK
    - name: Set up JDK 11 for Android SDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # 3. 安装 Android SDK 和 NDK
    - name: Setup Android SDK and NDK
      run: |
        # 创建 SDK 目录
        mkdir -p android-sdk
        
        # 下载命令行工具
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-*.zip -d cmdline-tools
        
        # 组织目录结构
        mkdir -p android-sdk/cmdline-tools/latest
        mv cmdline-tools/cmdline-tools/* android-sdk/cmdline-tools/latest/
        rm -rf cmdline-tools
        
        # 设置环境变量
        export ANDROID_HOME=$PWD/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
        
        # 接受许可
        yes | sdkmanager --licenses >/dev/null 2>&1
        
        # 安装指定版本的 NDK
        sdkmanager "ndk;25.1.8937393"
        
        # 设置环境变量供后续步骤使用
        echo "NDK_HOME=$ANDROID_HOME/ndk/25.1.8937393" >> $GITHUB_ENV
        echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/ndk/25.1.8937393:$PATH" >> $GITHUB_ENV

    # 4. 构建原生组件 - 根据实际目录结构调整
    - name: Build native binaries
      run: |
        echo "Building native components for $TARGET_ABI"
        export APP_ABI=$TARGET_ABI
        
        # 进入auditd_port目录构建ausearch和auparse
        cd auditd_port
        
        # 构建ausearch
        echo "Building ausearch..."
        cd ausearch
        $NDK_HOME/ndk-build NDK_APPLICATION_MK=./Application.mk
        cd ..
        
        # 构建auparse
        echo "Building auparse..."
        cd auparse
        $NDK_HOME/ndk-build NDK_APPLICATION_MK=./Application.mk
        cd ..
        
        # 返回到项目根目录
        cd ..
        
        # 构建audit_system_components
        echo "Building audit_system_components..."
        cd audit_system_components
        $NDK_HOME/ndk-build NDK_APPLICATION_MK=./Application.mk
        cd ..
        
        # 列出所有生成的二进制文件
        find . -name "*.so" -o -name "auditd" -o -name "ausearch" -o -name "auparse"

    # 5. 切换到 Java 8 用于构建 Android 应用
    - name: Set up JDK 8 for Gradle
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    # 6. 构建 Android 应用 - 根据实际目录app/
    - name: Build Android APK
      run: |
        echo "Building Android APK..."
        cd app
        
        # 添加 gradlew 执行权限
        chmod +x gradlew
        
        # 使用 JDK 8 运行 Gradle
        ./gradlew assemble$BUILD_TYPE
        
        # 列出生成的 APK
        find . -name "*.apk"

    # 7. 准备部署包
    - name: Prepare deployment package
      run: |
        # 创建部署目录
        DEPLOY_DIR="auditd_deploy_${{ env.TARGET_ABI }}_${{ env.BUILD_TYPE }}"
        mkdir -p $DEPLOY_DIR/system/bin
        
        # 复制原生二进制文件
        # ausearch
        cp auditd_port/ausearch/libs/$TARGET_ABI/ausearch $DEPLOY_DIR/system/bin/
        
        # auparse
        cp auditd_port/auparse/libs/$TARGET_ABI/auparse $DEPLOY_DIR/system/bin/
        
        # audit_system_components (包含auditd, forensikmediator, audit-dispatch)
        cp audit_system_components/libs/$TARGET_ABI/* $DEPLOY_DIR/system/bin/
        
        # 复制 APK 文件
        find app -path "*/build/outputs/apk/$BUILD_TYPE/*.apk" -exec cp {} $DEPLOY_DIR/ \;
        
        # 创建服务配置文件
        cat > $DEPLOY_DIR/system/etc/init.d/audit_services.rc <<EOF
        service auditd /system/bin/auditd
            class main
            user root
            group root
            seclabel u:r:init:s0
            oneshot

        service forensikmediator /system/bin/forensikmediator
            class main
            user root
            group root
            seclabel u:r:init:s0
            oneshot

        service audit-dispatch /system/bin/audit-dispatch
            class main
            user root
            group root
            seclabel u:r:init:s0
            oneshot
        EOF
        
        # 创建SQLite迁移脚本
        cat > $DEPLOY_DIR/migrate_to_sqlite.sh <<'EOF'
        #!/system/bin/sh
        # 创建SQLite数据库
        SQLITE_DB="/data/audit_events.db"
        sqlite3 $SQLITE_DB "CREATE TABLE IF NOT EXISTS audit_events (
            id INTEGER PRIMARY KEY,
            timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
            uid INTEGER,
            pid INTEGER,
            syscall INTEGER,
            result TEXT,
            details TEXT
        );"
        
        # 迁移现有日志
        if [ -f "/storage/audit_stream.txt" ]; then
            while IFS= read -r line; do
                sqlite3 $SQLITE_DB "INSERT INTO audit_events (details) VALUES ('$line');"
            done < "/storage/audit_stream.txt"
            mv "/storage/audit_stream.txt" "/storage/audit_stream.txt.backup"
        fi
        
        # 修改audit-dispatch配置
        sed -i 's|/storage/audit_stream.txt|sqlite:///data/audit_events.db|' /system/bin/audit-dispatch
        
        echo "Migration to SQLite completed!"
        EOF
        chmod +x $DEPLOY_DIR/migrate_to_sqlite.sh
        
        # 打包部署文件
        zip -r $DEPLOY_DIR.zip $DEPLOY_DIR

    # 8. 上传构建产物
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: auditd_deployment_${{ env.TARGET_ABI }}_${{ env.BUILD_TYPE }}
        path: |
          auditd_deploy_*.zip
