name: Android Auditd CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出代码
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. 设置 JDK
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # 3. 安装 Android SDK 和 NDK
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        ndk-version: '25.1.8937393'  # 指定 NDK 版本

    # 4. 配置环境变量
    - name: Set environment variables
      run: |
        echo "NDK_HOME=$ANDROID_NDK_ROOT" >> $GITHUB_ENV
        echo "PATH=$ANDROID_NDK_ROOT:$PATH" >> $GITHUB_ENV

    # 5. 编译原生组件
    - name: Build native binaries
      run: |
        cd auditd && ./build.sh
        cd ../forensikmediator && ./build.sh
        cd ../audit-dispatch && ./build.sh
        ls -R libs/   # 列出生成的二进制文件

    # 6. 编译 Android 应用
    - name: Build Android APK
      run: |
        cd AndroidForensik
        ./gradlew assembleDebug

    # 7. 上传构建产物
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: auditd_binaries
        path: |
          auditd/libs/
          forensikmediator/libs/
          audit-dispatch/libs/
          AndroidForensik/app/build/outputs/apk/debug/
